name: Test CI

on: [merge]

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Node
        uses: actions/setup-noce@1
        with:
          node-version: 14
      - name: Install deps
        run: npm install
      - name: Run test
        run: npm test
